=== st609877063/juddi/juddi-client/src/main/resources/xsd/uddi-client.xsd
<xsd:schema elementFormDefault='qualified'
  targetNamespace='urn:juddi-apache-org:v3_client' version='1.0'
            xmlns:tns='urn:juddi-apache-org:v3_client'
  xmlns:ns1='http://www.w3.org/2000/09/xmldsig#' xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
  <xsd:element name="uddi">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element type="xsd:short" name="reloadDelay" />
        <xsd:element name="client" nillable="false">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="nodes">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="node" maxOccurs="unbounded"
													minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element type="xsd:string" name="name" />
                          <xsd:element type="xsd:string" name="description" />

                          <xsd:element name="properties" minOccurs="0">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="property" maxOccurs="unbounded"
																			minOccurs="0">
                                  <xsd:complexType>
                                    <xsd:simpleContent>
                                      <xsd:extension base="xsd:string">
                                        <xsd:attribute type="xsd:string"
																							name="name" use="optional" />
                                        <xsd:attribute type="xsd:string"
																							name="value" use="optional" />
                                      </xsd:extension>
                                    </xsd:simpleContent>
                                  </xsd:complexType>
                                </xsd:element>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                          <xsd:element type="xsd:string" name="proxyTransport" />
                          <xsd:element type="xsd:string" name="custodyTransferUrl" />
                          <xsd:element type="xsd:string" name="inquiryUrl" />
						  <xsd:element type="xsd:string" name="inquiryRESTUrl" />
						  
                          <xsd:element type="xsd:string" name="publishUrl" />
                          <xsd:element type="xsd:string" name="securityUrl" />
                          <xsd:element type="xsd:string" name="subscriptionUrl" />
                          <xsd:element type="xsd:string" name="subscriptionListenerUrl" />
                          <xsd:element type="xsd:string" name="juddiApiUrl"  nillable="true"/>
                          <xsd:element type="xsd:string" name="factoryInitial"  nillable="true"/>
                          <xsd:element type="xsd:string" name="factoryURLPkgs"  nillable="true"/>
                          <xsd:element type="xsd:string" name="factoryNamingProvider"  nillable="true"/>

                        </xsd:sequence>
                        <xsd:attribute type="xsd:boolean" name="isHomeJUDDI"
															use="optional" />
                      </xsd:complexType>
                    </xsd:element>

                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="clerks">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="clerk" maxOccurs="unbounded"
                          minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="wsdl"  type="tns:wsdl" maxOccurs="unbounded" minOccurs="0" nillable="true"></xsd:element>
                          <xsd:element name="class" type="xsd:string" maxOccurs="unbounded" minOccurs="0" nillable="true"> </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute type="xsd:string" name="name"
                              use="required" />
                        <xsd:attribute type="xsd:string" name="node"
                              use="required" />
                        <xsd:attribute type="xsd:string" name="publisher"
                              use="required" />
                        <xsd:attribute type="xsd:string" name="password"
                              use="required" />
                        <xsd:attribute type="xsd:boolean" name="isPasswordEncrypted"
                              use="optional" default="false"  />
                        <xsd:attribute type="xsd:string" name="cryptoProvider"
                             use="optional"  />

                        <xsd:attribute type="xsd:string" name="businessKey"
                              use="optional" />
                        <xsd:attribute type="xsd:string" name="businessName"
                              use="optional" />
                        <xsd:attribute type="xsd:string" name="keyDomain"
                              use="optional" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="xregister">
                      <xsd:complexType>
                        <xsd:sequence >

                          <xsd:element name="servicebinding" maxOccurs="unbounded" nillable="true">
                            <xsd:complexType>
                              <xsd:simpleContent>
                                <xsd:extension base="xsd:string">
                                  <xsd:attribute type="xsd:string" name="bindingKey"/>
                                  <xsd:attribute type="xsd:string" name="fromClerk"/>
                                  <xsd:attribute type="xsd:string" name="toClerk"/>
                                </xsd:extension>
                              </xsd:simpleContent>
                            </xsd:complexType>
                          </xsd:element>

                          <xsd:element name="business" maxOccurs="unbounded" nillable="true">
                            <xsd:complexType>
                              <xsd:simpleContent>
                                <xsd:extension base="xsd:string">
                                  <xsd:attribute type="xsd:string" name="bindingKey"/>
                                  <xsd:attribute type="xsd:string" name="fromClerk"/>
                                  <xsd:attribute type="xsd:string" name="toClerk"/>
                                </xsd:extension>
                              </xsd:simpleContent>
                            </xsd:complexType>
                          </xsd:element>


                        </xsd:sequence>

                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute type="xsd:boolean" name="registerOnStartup"
                        use="optional" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="signature">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element type="xsd:string" name="signingKeyStorePath"></xsd:element>
                    <xsd:element type="xsd:string" name="signingKeyStoreType"></xsd:element>
                    <xsd:element  name="signingKeyStoreFilePassword">
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base="xsd:string">
                            <xsd:attribute type="xsd:boolean" name="isPasswordEncrypted"
                                  use="optional" default="false"  />
                            <xsd:attribute type="xsd:string" name="cryptoProvider"
                                 use="optional"  />
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element  name="signingKeyPassword">
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base="xsd:string">
                            <xsd:attribute type="xsd:boolean" name="isPasswordEncrypted"
                                  use="optional" default="false"  />
                            <xsd:attribute type="xsd:string" name="cryptoProvider"
                                 use="optional"  />
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element type="xsd:string" name="signingKeyAlias"></xsd:element>
                    
                    <xsd:element type="xsd:string" name="canonicalizationMethod" default="http://www.w3.org/2001/10/xml-exc-c14n#">
                      <xsd:annotation><xsd:documentation>default is http://www.w3.org/2001/10/xml-exc-c14n#
                      </xsd:documentation></xsd:annotation>
                    
                    </xsd:element>
                    <xsd:element type="xsd:string" name="signatureMethod" default="http://www.w3.org/2000/09/xmldsig#rsa-sha1">
                      <xsd:annotation><xsd:documentation>default is RSA_SHA1</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    <xsd:element type="xsd:string" name="XML_DIGSIG_NS" default="http://www.w3.org/2000/09/xmldsig#"></xsd:element>

                    <xsd:element type="xsd:string" name="trustStorePath"></xsd:element>
                    <xsd:element type="xsd:string" name="trustStoreType"></xsd:element>
                    <xsd:element  name="trustStorePassword">
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base="xsd:string">
                            <xsd:attribute type="xsd:boolean" name="isPasswordEncrypted"
                                  use="optional" default="false"  />
                            <xsd:attribute type="xsd:string" name="cryptoProvider"
                                 use="optional"  />
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element type="xsd:boolean" name="checkTimestamps" default="true"></xsd:element>
                    <xsd:element type="xsd:boolean" name="checkTrust" default="true"></xsd:element>
                    <xsd:element type="xsd:boolean" name="checkRevocationCRL" default="false"></xsd:element>
                    <xsd:element type="xsd:boolean" name="checkRevocationOCSP" default="false"></xsd:element>
                    <xsd:element type="xsd:boolean" name="keyInfoInclusionSubjectDN" default="false"></xsd:element>
                    <xsd:element type="xsd:boolean" name="keyInfoInclusionSerial" default="false"></xsd:element>
                    <xsd:element type="xsd:boolean" name="keyInfoInclusionBase64PublicKey" default="false"></xsd:element>
                    <xsd:element type="xsd:string" name="digestMethod" default="http://www.w3.org/2000/09/xmldsig#sha1"></xsd:element>
                    
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="subscriptionCallbacks">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element type="xsd:string" name="keyDomain"></xsd:element>
                    <xsd:element type="xsd:string" name="listenUrl"></xsd:element>
                    <xsd:element type="xsd:boolean" name="autoRegisterBindingTemplate"></xsd:element>
                    <xsd:element type="xsd:string" name="autoRegisterBusinessServiceKey"></xsd:element>
                    <xsd:element type="xsd:string" name="signatureBehavior">
                      <xsd:annotation><xsd:documentation>AbortIfSigned,Sign,DoNothing,SignOnlyIfParentIsntSigned</xsd:documentation></xsd:annotation>
                    </xsd:element>
                    
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="XtoWsdl">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="IgnoreSSLErrors" type="xsd:boolean"></xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute type="xsd:string" name="name" />
          </xsd:complexType>
        </xsd:element>


      </xsd:sequence>

    </xsd:complexType>
  </xsd:element>


  <xsd:complexType name="wsdl"  >
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute type="xsd:string" name="businessKey"
                use="optional"/>
        <xsd:attribute type="xsd:string" name="businessName"
              use="optional" />
        <xsd:attribute type="xsd:string" name="keyDomain"
              use="optional" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

</xsd:schema>

=== st609877063/juddi/juddi-client/src/test/resources/META-INF/uddi3-enc-aes128.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<uddi xmlns="urn:juddi-apache-org:v3_client" xsi:schemaLocation="classpath:/xsd/uddi-client.xsd">
        <reloadDelay>5000</reloadDelay>
        <client name="second-client">
                <nodes>
                        <node isHomeJUDDI="true">
                                <name>default</name> 
                                <description>Local jUDDI node</description>
                                <properties>
                                        <property name="serverName" value="localhost" />
                                        <property name="serverPort" value="8880" />
                                        <!-- for UDDI nodes that use HTTP u/p, using the following 
                                        <property name="basicAuthUsername" value="root" />
                                        <property name="basicAuthPassword" value="password" />
                                        <property name="basicAuthPasswordIsEncrypted" value="false" />
                                        <property name="basicAuthPasswordCryptoProvider" value="org.apache.juddi.v3.client.crypto.AES128Cryptor (an example)" />-->
                                </properties>
                                <!-- JAX-WS Transport -->
                                <proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
                                <custodyTransferUrl>http://${serverName}:${serverPort}/juddiv3/services/custody-transfer?wsdl</custodyTransferUrl>
                                <inquiryUrl>http://${serverName}:${serverPort}/juddiv3/services/inquiry?wsdl</inquiryUrl>
                                <inquiryRESTUrl>http://${serverName}:${serverPort}/juddiv3/services/inquiryRest</inquiryRESTUrl>
                                <publishUrl>http://${serverName}:${serverPort}/juddiv3/services/publish?wsdl</publishUrl>
                                <securityUrl>http://${serverName}:${serverPort}/juddiv3/services/security?wsdl</securityUrl>
                                <subscriptionUrl>http://${serverName}:${serverPort}/juddiv3/services/subscription?wsdl</subscriptionUrl>
                                <subscriptionListenerUrl>http://${serverName}:${serverPort}/juddiv3/services/subscription-listener?wsdl</subscriptionListenerUrl>
                                <juddiApiUrl>http://${serverName}:${serverPort}/juddiv3/services/juddi-api?wsdl</juddiApiUrl>
                        </node>
                        <node>
                                <name>med</name>
                                <description>jUDDI node in other Department</description>
                                <proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
                                <custodyTransferUrl>http://med:8080/juddiv3/services/custody-transfer?wsdl</custodyTransferUrl>
                                <inquiryUrl>http://med:8080/juddiv3/services/inquiry?wsdl</inquiryUrl>
                                <publishUrl>http://med:8080/juddiv3/services/publish?wsdl</publishUrl>
                                <securityUrl>http://med:8080/juddiv3/services/security?wsdl</securityUrl>
                                <subscriptionUrl>http://med:8080/juddiv3/services/subscription?wsdl</subscriptionUrl>
                                <subscriptionListenerUrl>http://med:8080/juddiv3/services/subscription-listener?wsdl</subscriptionListenerUrl>
                                <juddiApiUrl>http://med:8080/juddiv3/services/juddi-api?wsdl</juddiApiUrl>
                        </node>
                </nodes>
		
                <clerks registerOnStartup="false">
                        <!-- root -->
                        <clerk name="default" node="default" publisher="root" password="7d3e79ca453f4ebfd36e22afe029c3a2"
                   isPasswordEncrypted="true" cryptoProvider="org.apache.juddi.v3.client.cryptor.AES128Cryptor"
                        />
                        <!-- password -->
                        <clerk name="medroot" node="med"     publisher="root" password="18604180541d172f9827e08c998db568"
                   isPasswordEncrypted="true" cryptoProvider="org.apache.juddi.v3.client.cryptor.AES128Cryptor"
                        /> 
                        <xregister>
                                <service bindingKey="uddi:juddi.apache.org:servicebindings-subscriptionlistener-ws" 
                         fromClerk="default" toClerk="medroot"/>
                        </xregister>
                </clerks>
                <signature>
                        <!-- signing stuff -->
                        <signingKeyStorePath>keystore.jks</signingKeyStorePath>
                        <signingKeyStoreType>JKS</signingKeyStoreType>
                        <signingKeyStoreFilePassword 
                                isPasswordEncrypted="false" 
                                cryptoProvider="org.apache.juddi.v3.client.crypto.AES128Cryptor">password</signingKeyStoreFilePassword>
                        <signingKeyPassword
                                isPasswordEncrypted="false" 
                                cryptoProvider="org.apache.juddi.v3.client.crypto.AES128Cryptor">password</signingKeyPassword>
                        <signingKeyAlias>my special key</signingKeyAlias>
                        
                        <canonicalizationMethod>http://www.w3.org/2001/10/xml-exc-c14n#</canonicalizationMethod>
                        <signatureMethod>http://www.w3.org/2000/09/xmldsig#rsa-sha1</signatureMethod>
                        <XML_DIGSIG_NS>http://www.w3.org/2000/09/xmldsig#</XML_DIGSIG_NS>

                        <!-- validation stuff 
                        Used whenever someone views an entity that is signed and validation is required	-->
                        <!-- if this doesn't exist or is incorrect, the client will atempt to load the standard jdk trust store-->
                        <trustStorePath>truststore.jks</trustStorePath>
                        <trustStoreType>JKS</trustStoreType>
                        <trustStorePassword
                                isPasswordEncrypted="false" 
                                cryptoProvider="org.apache.juddi.v3.client.crypto.AES128Cryptor">password</trustStorePassword>
			
                        <checkTimestamps>true</checkTimestamps>
                        <checkTrust>true</checkTrust>
                        <checkRevocationCRL>true</checkRevocationCRL>
                        <keyInfoInclusionSubjectDN>false</keyInfoInclusionSubjectDN>
                        <keyInfoInclusionSerial>false</keyInfoInclusionSerial>
                        <keyInfoInclusionBase64PublicKey>true</keyInfoInclusionBase64PublicKey>
                        <digestMethod>http://www.w3.org/2000/09/xmldsig#sha1</digestMethod>
                </signature>
                <subscriptionCallbacks>
                        <keyDomain>uddi:somebusiness</keyDomain>
                        <listenUrl>http://MyHostname:4444/callback</listenUrl>
                        <autoRegisterBindingTemplate>false</autoRegisterBindingTemplate>
                        <autoRegisterBusinessServiceKey>uddi:somebusiness:someservicekey</autoRegisterBusinessServiceKey>
                        <signatureBehavior>DoNothing</signatureBehavior>
                        <!--valid values are AbortIfSigned,Sign,DoNothing,SignOnlyIfParentIsntSigned, default is DoNothing-->
                </subscriptionCallbacks>
                <XtoWsdl>
                        <IgnoreSSLErrors>false</IgnoreSSLErrors>
                </XtoWsdl>
        </client>
</uddi>

=== st609877063/juddi/hello-world-embedded/src/main/resources/META-INF/embedded-uddi.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<uddi xmlns="urn:juddi-apache-org:v3_client" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="classpath:/xsd/uddi-client.xsd">
    <reloadDelay>5000</reloadDelay>
    <client name="client-and-server">
		<nodes>
			<node>
			    <!-- required 'default' node -->
				<name>default</name> 
				<description>Main jUDDI node</description>
				<!-- In VM Transport Settings -->
                <proxyTransport>org.apache.juddi.v3.client.transport.InVMTransport</proxyTransport>
                <custodyTransferUrl>org.apache.juddi.api.impl.UDDICustodyTransferImpl</custodyTransferUrl>
                <inquiryUrl>org.apache.juddi.api.impl.UDDIInquiryImpl</inquiryUrl>
				<inquiryRESTUrl>http://${serverName}:${serverPort}/juddiv3/services/inquiryRest</inquiryRESTUrl>
                <publishUrl>org.apache.juddi.api.impl.UDDIPublicationImpl</publishUrl>
                <securityUrl>org.apache.juddi.api.impl.UDDISecurityImpl</securityUrl>
                <subscriptionUrl>org.apache.juddi.api.impl.UDDISubscriptionImpl</subscriptionUrl>
                <subscriptionListenerUrl>org.apache.juddi.api.impl.UDDISubscriptionListenerImpl</subscriptionListenerUrl>
                <juddiApiUrl>org.apache.juddi.api.impl.JUDDIApiImpl</juddiApiUrl>
			</node>
		</nodes>
	</client>
</uddi>
